apiVersion: v1
kind: Service
metadata:
  name: {{ include "langfuse.fullname" . }}-web
  namespace: {{ include "common.names.namespace" . }}
  labels:
    {{- include "langfuse.labels" . | nindent 4 }}
    {{- with .Values.service.additionalLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- if .Values.service.annotations }}
  annotations:
    {{- toYaml .Values.service.annotations | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.langfuse.web.port }}
      protocol: TCP
      name: http
  selector:
    {{- include "langfuse.selectorLabels" . | nindent 4 }}
    app: web
